# Generated by Django 2.2 on 2020-06-13 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('juego', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AvalonUser',
            new_name='UsuarioAvaloncete',
        ),
    ]
